# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 610ea1508b51bd9469401cd0382be6ab77d5c414d6bbb5c6ed5d0921b768e8772768b518ca970188f7b86962e7d0c2cc28e646e6d6eff3c2009b7525a7bec599

test:
  secret_key_base: 8f47fad7b4b8392b02282f264c3abb545f422d7f406f87f6d30ce64bf67a7fa7f66638fbbeb9871b41844fe9d17f87f354409b1ceee1f5f3277a7e357171cec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
